services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: multibranches
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - multibranches_pgdata:/var/lib/postgresql/data

volumes:
  multibranches_pgdata:
