# Generated by Django 5.2.17 on 2026-08-17 12:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'partners',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('whatsapp_group', models.CharField(blank=True, db_column='wtsappgroup', max_length=255)),
                ('is_profit_sharing', models.BooleanField(default=False, help_text='When true, this group is used for monthly partner wage calculation.')),
            ],
            options={
                'db_table': 'partner_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerGroupEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_percent', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_group_entries', to='institutions.institution')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_entries', to='partners.partner')),
                ('partner_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='partners.partnergroup')),
            ],
            options={
                'db_table': 'partner_group_entries',
                'indexes': [models.Index(fields=['institution', 'partner_group', 'is_active'], name='partner_gro_institu_02388c_idx'), models.Index(fields=['partner'], name='partner_gro_partner_d9949d_idx')],
                'constraints': [models.UniqueConstraint(fields=('partner_group', 'institution', 'partner'), name='uniq_group_institution_partner')],
            },
        ),
    ]
