# Generated by Django 5.2.17 on 2026-08-17 12:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessWage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('wages_month', models.PositiveSmallIntegerField()),
                ('wages_year', models.PositiveSmallIntegerField()),
                ('total_receipt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_business', models.DecimalField(decimal_places=2, max_digits=18)),
                ('business_percent', models.DecimalField(decimal_places=4, help_text='Partner share percent at the time of confirmation.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('partner_wage_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_entered', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(db_column='for_inst_id', on_delete=django.db.models.deletion.PROTECT, related_name='business_wages', to='institutions.institution')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_wages', to='partners.partner')),
            ],
            options={
                'db_table': 'business_wages',
                'indexes': [models.Index(fields=['institution', 'wages_year', 'wages_month'], name='business_wa_for_ins_2be805_idx'), models.Index(fields=['partner'], name='business_wa_partner_005ee2_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'partner', 'wages_year', 'wages_month'), name='uniq_wage_institution_partner_period'), models.CheckConstraint(condition=models.Q(('wages_month__gte', 1), ('wages_month__lte', 12)), name='chk_wages_month_range')],
            },
        ),
    ]
